name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ffdccf4e45568ccc7978f90dd3bf9dfce2bede1884955767123e19becc39a14"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
