name = "Greg's Factory"
author = "Greg's Factory Authors"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8e08c95978c9ee174ce9a924df356e2c08bf4ae6a242ba95405d66103e600d9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
