import gregtech.api.metatileentity.MetaTileEntity
import gregtech.api.metatileentity.interfaces.IGregTechTileEntity
import gregtech.api.metatileentity.multiblock.IMultiblockPart
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController
import gregtech.api.pattern.BlockPattern
import gregtech.api.pattern.FactoryBlockPattern
import gregtech.api.recipes.builders.ComputationRecipeBuilder
import gregtech.api.recipes.RecipeMap

import gregtech.client.renderer.texture.Textures
import gregtech.client.renderer.texture.cube.SimpleOverlayRenderer
import gregtech.client.renderer.ICubeRenderer

import gregtech.common.blocks.BlockGlassCasing
import gregtech.common.blocks.BlockFusionCasing
import gregtech.common.blocks.MetaBlocks

import net.minecraft.util.ResourceLocation

import net.minecraftforge.fml.relauncher.Side
import net.minecraftforge.fml.relauncher.SideOnly



// import classes.QilbyRecipeMaps

public class MetaTileEntityBlackHoleGeneratorMkI extends RecipeMapMultiblockController {

    private static final RecipeMap<ComputationRecipeBuilder> RECIPE_MAP = new RecipeMap<>(
        "black_hole_generator_1",
        2, 0, 2, 1,
        new ComputationRecipeBuilder(),
        false
    )
    
    public MetaTileEntityBlackHoleGeneratorMkI(ResourceLocation metaTileEntityId) {
        super(metaTileEntityId, RECIPE_MAP)
    }

    @Override
    public MetaTileEntity createMetaTileEntity(IGregTechTileEntity tileEntity) {
        return new MetaTileEntityBlackHoleGeneratorMkI(metaTileEntityId)
    }

    @Override
    protected BlockPattern createStructurePattern() {
        return FactoryBlockPattern.start()
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                 A                 ",
                "                BAB                ",
                "             AAAAAAAAA             ",
                "                BAB                ",
                "                 A                 ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                ACA                ",
                "             AAAACAAAA             ",
                "           AACCCCCCCCCAA           ",
                "             AAAACAAAA             ",
                "                ACA                ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                 A                 ",
                "           AA   AAA   AA           ",
                "         AACCAAAAAAAAACCAA         ",
                "           AA   AAA   AA           ",
                "                 A                 ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "         AA             AA         ",
                "       AACCAA         AACCAA       ",
                "         AA             AA         ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "       AA                 AA       ",
                "      ACCAA             AACCA      ",
                "       AA                 AA       ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "      A                     A      ",
                "     ACAA                 AACA     ",
                "      A                     A      ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "     A                       A     ",
                "    ACA                     ACA    ",
                "     A                       A     ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "    A                         A    ",
                "   ACA                       ACA   ",
                "    A                         A    ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "    A                         A    ",
                "   ACA                       ACA   ",
                "    A                         A    ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "   A                           A   ",
                "  ACA                         ACA  ",
                "   A                           A   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "   A                           A   ",
                "  ACA                         ACA  ",
                "   A                           A   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "  A                             A  ",
                " ACA                           ACA ",
                "  A                             A  ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "  A                             A  ",
                " ACA                           ACA ",
                "  A                             A  ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   "
            )
            .aisle(
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                " A                               A ",
                "ACA                             ACA",
                " A                               A ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 "
            )
            .aisle(
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                " A                               A ",
                "ACA                             ACA",
                " A                               A ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 "
            )
            .aisle(
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                " A                               A ",
                "ACA                             ACA",
                " A                               A ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 "
            )
            .aisle(
                "                BAB                ",
                "             AAAACAAAA             ",
                "           AA   AAA   AA           ",
                "         AA             AA         ",
                "       AA                 AA       ",
                "      A                     A      ",
                "     A                       A     ",
                "    A                         A    ",
                "    A                         A    ",
                "   A                           A   ",
                "   A                           A   ",
                "  A                             A  ",
                "  A                             A  ",
                " A                               A ",
                " A                               A ",
                " A                               A ",
                "BAA                             AAB",
                "ACA                             ACA",
                "BAA                             AAB",
                " A                               A ",
                " A                               A ",
                " A                               A ",
                "  A                             A  ",
                "  A                             A  ",
                "   A                           A   ",
                "   A                           A   ",
                "    A                         A    ",
                "    A                         A    ",
                "     A                       A     ",
                "      A                     A      ",
                "       AA                 AA       ",
                "         AA             AA         ",
                "           AA   AAA   AA           ",
                "             AAAACAAAA             ",
                "                BAB                "
            )
            .aisle(
                "             AAAAAAAAA             ",
                "           AACCCCCCCCCAA           ",
                "         AACCAAAAAAAAACCAA         ",
                "       AACCAA         AACCAA       ",
                "      ACCAA             AACCA      ",
                "     ACAA                 AACA     ",
                "    ACA                     ACA    ",
                "   ACA                       ACA   ",
                "   ACA                       ACA   ",
                "  ACA                         ACA  ",
                "  ACA                         ACA  ",
                " ACA                           ACA ",
                " ACA                           ACA ",
                "ACA                             ACA",
                "ACA                             ACA",
                "ACA                             ACA",
                "ACA                             ACA",
                "ACA                             ACA",
                "ACA                             ACA",
                "ACA                             ACA",
                "ACA                             ACA",
                "ACA                             ACA",
                " ACA                           ACA ",
                " ACA                           ACA ",
                "  ACA                         ACA  ",
                "  ACA                         ACA  ",
                "   ACA                       ACA   ",
                "   ACA                       ACA   ",
                "    ACA                     ACA    ",
                "     ACAA                 AACA     ",
                "      ACCAA             AACCA      ",
                "       AACCAA         AACCAA       ",
                "         AACCAAAAAAAAACCAA         ",
                "           AACCCCCCCCCAA           ",
                "             AAAADAAAA             "
            )
            .aisle(
                "                BAB                ",
                "             AAAACAAAA             ",
                "           AA   AAA   AA           ",
                "         AA             AA         ",
                "       AA                 AA       ",
                "      A                     A      ",
                "     A                       A     ",
                "    A                         A    ",
                "    A                         A    ",
                "   A                           A   ",
                "   A                           A   ",
                "  A                             A  ",
                "  A                             A  ",
                " A                               A ",
                " A                               A ",
                " A                               A ",
                "BAA                             AAB",
                "ACA                             ACA",
                "BAA                             AAB",
                " A                               A ",
                " A                               A ",
                " A                               A ",
                "  A                             A  ",
                "  A                             A  ",
                "   A                           A   ",
                "   A                           A   ",
                "    A                         A    ",
                "    A                         A    ",
                "     A                       A     ",
                "      A                     A      ",
                "       AA                 AA       ",
                "         AA             AA         ",
                "           AA   AAA   AA           ",
                "             AAAACAAAA             ",
                "                BAB                "
            )
            .aisle(
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                " A                               A ",
                "ACA                             ACA",
                " A                               A ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 "
            )
            .aisle(
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                " A                               A ",
                "ACA                             ACA",
                " A                               A ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 "
            )
            .aisle(
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                " A                               A ",
                "ACA                             ACA",
                " A                               A ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 "
            )
            .aisle(
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "  A                             A  ",
                " ACA                           ACA ",
                "  A                             A  ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "  A                             A  ",
                " ACA                           ACA ",
                "  A                             A  ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "   A                           A   ",
                "  ACA                         ACA  ",
                "   A                           A   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "   A                           A   ",
                "  ACA                         ACA  ",
                "   A                           A   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "    A                         A    ",
                "   ACA                       ACA   ",
                "    A                         A    ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "    A                         A    ",
                "   ACA                       ACA   ",
                "    A                         A    ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "     A                       A     ",
                "    ACA                     ACA    ",
                "     A                       A     ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "      A                     A      ",
                "     ACAA                 AACA     ",
                "      A                     A      ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "       AA                 AA       ",
                "      ACCAA             AACCA      ",
                "       AA                 AA       ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "         AA             AA         ",
                "       AACCAA         AACCAA       ",
                "         AA             AA         ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                 A                 ",
                "           AA   AAA   AA           ",
                "         AACCAAAAAAAAACCAA         ",
                "           AA   AAA   AA           ",
                "                 A                 ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                ACA                ",
                "                ACA                ",
                "                ACA                ",
                "             AAAACAAAA             ",
                "           AACCCCCCCCCAA           ",
                "             AAAACAAAA             ",
                "                ACA                ",
                "                ACA                ",
                "                ACA                ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .aisle(
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                 A                 ",
                "                 A                 ",
                "                 A                 ",
                "                BAB                ",
                "             AAAAAAAAA             ",
                "                BAB                ",
                "                 A                 ",
                "                 A                 ",
                "                 A                 ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   ",
                "                                   "
            )
            .where(' ' as char, air())
            .where('A' as char, states(MetaBlocks.FUSION_CASING.getState(BlockFusionCasing.CasingType.FUSION_CASING)))
            .where('B' as char, states(MetaBlocks.FUSION_CASING.getState(BlockFusionCasing.CasingType.FUSION_CASING)).or(autoAbilities()))
            .where('C' as char, states(MetaBlocks.FUSION_CASING.getState(BlockFusionCasing.CasingType.FUSION_COIL)))
            .where('D' as char, selfPredicate())
            .build()
    }

    @Override
    @SideOnly(Side.CLIENT)
    public ICubeRenderer getBaseTexture(IMultiblockPart sourcePart){
        return Textures.FUSION_TEXTURE
    }
}
